### ISSUE TITLE
Errors in the console log

### ISSUE THREAD

**Issue by KuroKen91** [FruityRaptors/OneRoof#25]
Getting errors in the console whenever a chat has no messages yet. 

A small error but perhaps we can squash it sometime?

**Comment by jaysutham** [comment]
<img width="410" alt="Screen Shot 2021-07-05 at 8 34 14 AM" src="https://user-images.githubusercontent.com/73651163/124402539-cf0e6b80-dd6b-11eb-981d-3d4f99ec9143.png">

Is it this error?

**Comment by KuroKen91** [comment]
Yeap. That was the one I was thinking of.

**Comment by jaysutham** [comment]
Fixed in latest pull request
